{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-1.0.aar",
          "url": "android_release-1.0.aar",
          "size": 1133634,
          "sha512": "1549745101dc5fe83caa9ef77afc973ee538e4e0057d24575b5ecbfdfff82f7f2a7f76301603fbe3c364ca1432361c4ec771dff6d8b83972ea4ce23bb590b9ee",
          "sha256": "2644d6f8da4ee0fe34825d7931e78679d5d6497354608adfe00ae8ed3caf2e35",
          "sha1": "43501aaaa97cf1c14773ed11c7a3cc0b8532532b",
          "md5": "0e858b074d8b08f095188513573cefd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-1.0.aar",
          "url": "android_release-1.0.aar",
          "size": 1133634,
          "sha512": "1549745101dc5fe83caa9ef77afc973ee538e4e0057d24575b5ecbfdfff82f7f2a7f76301603fbe3c364ca1432361c4ec771dff6d8b83972ea4ce23bb590b9ee",
          "sha256": "2644d6f8da4ee0fe34825d7931e78679d5d6497354608adfe00ae8ed3caf2e35",
          "sha1": "43501aaaa97cf1c14773ed11c7a3cc0b8532532b",
          "md5": "0e858b074d8b08f095188513573cefd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-1.0-sources.jar",
          "url": "android_release-1.0-sources.jar",
          "size": 284058,
          "sha512": "c5e1e6a7d81accefb266acdf35334c60e830c9751d8daf61cc21aed27a7d745d0d9fc168849aec23c0ddc983dca66234af1d9a91a9bc261ab11fc8339e9fb63a",
          "sha256": "9fcbfd465a1eff6c0715f37aa2f70db86f55229af84f22c245b7dfb449bb00bb",
          "sha1": "56128694d6c53ba69e81a2f7bdacb986b5558cc7",
          "md5": "5ee68d6daf52b42457306a46f0e79262"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-1.0-javadoc.jar",
          "url": "android_release-1.0-javadoc.jar",
          "size": 2024915,
          "sha512": "10b5609b1d95458a1bb6ec7e3d7a280e8c1079b3a22fb014acb55755ee91fb86bd2773f808a90bc5a981abd8626b2d233ffea46d42091bf4677cbbfcba245a6b",
          "sha256": "eeb8916353ac22fdf01dab77040d42a11dcc3a370c8ae5287056935644ad66a4",
          "sha1": "430eff229e3246f7153fc534228527150376899a",
          "md5": "6cbf18f87cbc4c2125efcdb102daba74"
        }
      ]
    }
  ]
}
